### ISSUE TITLE
tcsh is not supported

### ISSUE THREAD

**Issue by drphilmarshall** [jchiang87/Primes#1]
`source setup/setup.sh` fails for users running the tcsh. I've seen this solved by DM by providing setup scripts in both `bash` and `tcsh`. Is it possible to  type
```
bash setup/setup.sh
```
and have your environment set up correctly regardless of your personal shell choice?

**Comment by jchiang87** [comment]
Ok, I'll add a setup.csh script too.   But if you do
```
bash --rcfile setup/setup.sh
```
it will work for this simple repo, but you'll get a fresh bash session, so any other set up or environment variables will be lost.

**Comment by drphilmarshall** [comment]
Yep, that worked:
```
bash --rcfile setup/setup.sh

bash-3.2$ nosetests .

```

gave me:

```....

----------------------------------------------------------------------

Ran 4 tests in 0.020s


OK
```

:-)

**Comment by jchiang87** [comment]
I just pushed a `setup/setup.csh`.  Can you try it?  It works on my laptop, but it is failing on my slac desktop box for reasons I don't understand.

**Comment by drphilmarshall** [comment]
PR is in #2 :-)

**Comment by jchiang87** [comment]
Did it work for you on tcsh?  I'm still trying to figure out why it's failing on slac linux. (It used to work in the DESC/Recipes repo).
